spring:
  application:
    name: config-client
  cloud:
    config:
      lable: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enable: true
        serviceId: service-config
server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/