eureka:
  client:
    defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /eureka-client-alias/**
      serviceId: eureka-client
    api-b:
      path: /service-feign/**
      serviceId: service-feign
